# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190924_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUSpecValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='SKU规格名称值')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SKU', verbose_name='sku')),
            ],
            options={
                'verbose_name': 'SKU规格属性值表',
                'verbose_name_plural': 'SKU规格属性值表',
                'db_table': 'DDSC_SKU_SPEC_VALUE',
            },
        ),
        migrations.CreateModel(
            name='SPUSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spec_name', models.CharField(max_length=20, verbose_name='SPU规格名称')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SPU', verbose_name='SPU')),
            ],
            options={
                'verbose_name': 'SPU规格',
                'verbose_name_plural': 'SPU规格',
                'db_table': 'DDSC_SPU_SPEC',
            },
        ),
        migrations.AddField(
            model_name='skuspecvalue',
            name='spu_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SPUSpec', verbose_name='SPU规格名称'),
        ),
    ]
