# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191011_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='weibouser',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='weibouser',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RemoveField(
            model_name='weibouser',
            name='weibo_token',
        ),
        migrations.AlterField(
            model_name='weibouser',
            name='uid',
            field=models.CharField(max_length=10, verbose_name='微博uid'),
        ),
    ]
