# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人')),
                ('address', models.CharField(max_length=100, verbose_name='收件地址')),
                ('isDefault', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('postcode', models.CharField(max_length=6, verbose_name='邮编')),
                ('receiver_mobile', models.CharField(max_length=11, verbose_name='联系人电话')),
                ('tag', models.CharField(max_length=10, verbose_name='标签')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
