# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-05 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuid', models.CharField(db_index=True, max_length=50, verbose_name='微博用户id')),
                ('access_token', models.CharField(max_length=100, verbose_name='授权令牌')),
                ('uid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'weibo_user',
            },
        ),
    ]
