# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191117_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibouser',
            name='uid',
            field=models.CharField(default=None, max_length=10, verbose_name='微博uid'),
        ),
    ]
