# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191118_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibouser',
            name='access_token',
            field=models.CharField(default=None, max_length=10, verbose_name='微博授权密钥'),
        ),
        migrations.AddField(
            model_name='weibouser',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='用户id'),
        ),
    ]
