# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191120_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibouser',
            name='uid',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='微博uid'),
        ),
    ]
