# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-14 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190929_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='is_commented',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='score',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '订单完成')], verbose_name='订单状态'),
        ),
    ]
