# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191114_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
